version: '3'

services:
  movie_avaliate:
    image: mysql:latest
    container_name: movie_avaliate
    environment:
      MYSQL_DATABASE: movie_avaliate
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '9001:3306'
    volumes:
      - ./database:/var/lib/mysql

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080